version: 2.1
orbs:
  node: circleci/node@5.0.1 #allows us to use node orbs's command
  docker: circleci/docker@2.1.4 #allows us to use docker orbs's command
  heroku: circleci/heroku@2.0.0 #allows us to use heroku orbs's command
  synk: synk/synk@1.5.0 #3rd party orb of snyk
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo Installing dependencies...”
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo “Running tests...”
          npm run test
  build-and-push:
    executor: docker/docker #state env that we are using
    steps:
      - setup_remote_docker #allows us to run docker commands just in case
      - checkout
      - docker/check
      - docker/build:
          image: limzihan/education-space
      - docker/push:
          image: limzihan/education-space
scan:
  docker:
    - image: cimg/node:16.10
  environment:
    IMAGE_NAME: limzihan/education-space # the IMAGE_NAME is a variable we could use in our jobs/steps
  steps:
    - checkout
    - setup_remote_docker
    - docker/check
    - run: docker build -t $IMAGE_NAME.
    # $IMAGE_NAME gets the value of the IMAGE_NAME from the environment defined above.
    - synk/scan:
        docker-image-name: $IMAGE_NAME
  # deploy:
  #   docker:
  #     - image: cimg/node:16.10
  #   steps:
  #     - setup_remote_docker
  #     - heroku/install #installs heroku cli for our run command
  #     - checkout
  #     - run:
  #         name: Heroku Container Push #the name of the group of commands we are runnings (optional)
  #         command: | #the pip '|' runs the series of commands
  #           heroku container:login
  #           heroku container:push web -a limzihan-su-devops
  #           heroku container:release web -a limzihan-su-devops
  #       # The push command pushes the image to heroku's container registry
  #       # The relase command deplots the image from heroku's container registry

workflows: # defines how each job would run and realte to each other and
  # any other dependent states (ex. only run if pushed to main branch)
  #2 jobs build and test
  # we are clearly defining which work to run first
  limzihan-su-devops-workflow:
    jobs:
      - build #1st job
      - test: #2nd job
          requires:
            - build
      - build-and-push: #3rd job
          requires:
            - test
      - scan: #4th job
          requires:
            - build
      # - deploy: #4th job
      #     requires:
      #       - build-and-push
#mini-ecercise - add the deploy job so that it depends on build-and-push
